use("hotel"); //hotel

db.habitaciones.insertMany([
  {
    codigo: "HAB001",
    nombre: "Odin",
    categoria: "Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
      { numCamas: 2, nombre: "Twin" },
    ],
    tamanyo: 200,
    servicios: [
      "Terraza",
      "Mesa de Billar",
      "Zona Spa",
      "Servicio Premium de Habitaciones",
      "Aire Acondicionado",
      "Bar",
      "Televisión",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "Gimnasio",
      "Piscina infinita climatizada",
    ],
    numPersonas: 6,
    precio: 1000,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/odin-suite-android1.jpg",
        "https://example.com/odin-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/odin-suite-wpf1.jpg",
        "https://example.com/odin-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB002",
    nombre: "Thor",
    categoria: "Junior Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
    ],
    tamanyo: 100,
    servicios: [
      "Terraza",
      "Servicio Premium de Habitaciones",
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "Cocina",
    ],
    numPersonas: 4,
    precio: 625,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB003",
    nombre: "Freyja",
    categoria: "Junior Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
    ],
    tamanyo: 100,
    servicios: [
      "Terraza",
      "Servicio Premium de Habitaciones",
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "Cocina",
    ],
    numPersonas: 4,
    precio: 625,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB004",
    nombre: "Loki",
    categoria: "Junior Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
    ],
    tamanyo: 100,
    servicios: [
      "Terraza",
      "Servicio Premium de Habitaciones",
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "Cocina",
    ],
    numPersonas: 4,
    precio: 625,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB005",
    nombre: "Balder",
    categoria: "Junior Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
    ],
    tamanyo: 100,
    servicios: [
      "Terraza",
      "Servicio Premium de Habitaciones",
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "Cocina",
    ],
    numPersonas: 4,
    precio: 625,
    descripcion: "Lorem",
    imagenes: [
      { url: "https://example.com/balder-suite1.jpg", plataforma: "general" },
      { url: "https://example.com/balder-suite2.jpg", plataforma: "general" },
    ],
    habilitada: true,
  },
  {
    codigo: "HAB006",
    nombre: "Huginn",
    categoria: "Estándar",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: [
      { logo: "xxxxx", descripcion: "Aire Acondicionado" },
      { logo: "xxxxx", descripcion: "Televisión" },
      { logo: "xxxxx", descripcion: "Cafetera" },
      { logo: "xxxxx", descripcion: "Minibar" },
      { logo: "xxxxx", descripcion: "WiFi" },
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB007",
    nombre: "Muninn",
    categoria: "Estándar",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: [
      { logo: "xxxxx", descripcion: "Aire Acondicionado" },
      { logo: "xxxxx", descripcion: "Televisión" },
      { logo: "xxxxx", descripcion: "Cafetera" },
      { logo: "xxxxx", descripcion: "Minibar" },
      { logo: "xxxxx", descripcion: "WiFi" },
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB008",
    nombre: "Geri",
    categoria: "Estándar",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: [
      { logo: "xxxxx", descripcion: "Aire Acondicionado" },
      { logo: "xxxxx", descripcion: "Televisión" },
      { logo: "xxxxx", descripcion: "Cafetera" },
      { logo: "xxxxx", descripcion: "Minibar" },
      { logo: "xxxxx", descripcion: "WiFi" },
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB009",
    nombre: "Rafn",
    categoria: "Estándar",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: [
      { logo: "xxxxx", descripcion: "Aire Acondicionado" },
      { logo: "xxxxx", descripcion: "Televisión" },
      { logo: "xxxxx", descripcion: "Cafetera" },
      { logo: "xxxxx", descripcion: "Minibar" },
      { logo: "xxxxx", descripcion: "WiFi" },
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB010",
    nombre: "Valravn",
    categoria: "Estándar",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: [
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Minibar",
      "WiFi",
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB011",
    nombre: "Sköll",
    categoria: "Estándar",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: [
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Minibar",
      "WiFi",
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB012",
    nombre: "Dellingr",
    categoria: "Estándar",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: [
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Minibar",
      "WiFi",
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB013",
    nombre: "Svanr",
    categoria: "Estándar",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: [
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Minibar",
      "WiFi",
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB014",
    nombre: "Gjallar",
    categoria: "Estándar",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: [
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Minibar",
      "WiFi",
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB015",
    nombre: "Arvakr",
    categoria: "Estándar",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: [
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Minibar",
      "WiFi",
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
  {
    codigo: "HAB016",
    nombre: "Fenrir",
    categoria: "Estándar",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: [
      "Aire Acondicionado",
      "Televisión",
      "Cafetera",
      "Minibar",
      "WiFi",
    ],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: {
      android: [
        "https://example.com/thor-suite-android1.jpg",
        "https://example.com/thor-suite-android2.jpg",
      ],
      wpf: [
        "https://example.com/thor-suite-wpf1.jpg",
        "https://example.com/thor-suite-wpf2.jpg",
      ],
    },
    habilitada: true,
  },
]);