//using hotel database
use("asgard");

//delete all rooms
db.habitaciones.deleteMany({});

//insert rooms
db.habitaciones.insertMany([
  {
    codigo: "HAB001",
    nombre: "Odin",
    categoria: "Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
      { numCamas: 2, nombre: "Twin" },
    ],
    tamanyo: 200,
    servicios: [
      "Balcón",
      "Mesa de Billar",
      "Spa",
      "Servicio Premium de Habitaciones",
      "AC",
      "Bar",
      "TV",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "GYM",
      "Piscina",
    ],
    numPersonas: 6,
    precio: 1000,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/S4Mv1Yfj/suite-Odin-Room.png",
      "https://i.ibb.co/S4Mv1Yfj/suite-Odin-Room.png",
      "https://i.ibb.co/S4Mv1Yfj/suite-Odin-Room.png",
      "https://i.ibb.co/S4Mv1Yfj/suite-Odin-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB002",
    nombre: "Thor",
    categoria: "Junior Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
    ],
    tamanyo: 100,
    servicios: [
      "Balcón",
      "Servicio Premium de Habitaciones",
      "AC",
      "TV",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "Cocina",
    ],
    numPersonas: 4,
    precio: 625,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB003",
    nombre: "Freyja",
    categoria: "Junior Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
    ],
    tamanyo: 100,
    servicios: [
      "Balcón",
      "Servicio Premium de Habitaciones",
      "AC",
      "TV",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "Cocina",
    ],
    numPersonas: 4,
    precio: 625,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB004",
    nombre: "Loki",
    categoria: "Junior Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
    ],
    tamanyo: 100,
    servicios: [
      "Balcón",
      "Servicio Premium de Habitaciones",
      "AC",
      "TV",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "Cocina",
    ],
    numPersonas: 4,
    precio: 625,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB005",
    nombre: "Balder",
    categoria: "Junior Suite",
    camas: [
      { numCamas: 1, nombre: "King" },
      { numCamas: 1, nombre: "Queen" },
    ],
    tamanyo: 100,
    servicios: [
      "Balcón",
      "Servicio Premium de Habitaciones",
      "AC",
      "TV",
      "Cafetera",
      "Nevera",
      "Oficina",
      "WiFi",
      "Cocina",
    ],
    numPersonas: 4,
    precio: 625,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
      "https://i.ibb.co/ynpjK04r/junior-Suite.jpg",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB006",
    nombre: "Heimdall",
    categoria: "Premium",
    camas: [
      { numCamas: 1, nombre: "Double" },
      { numCamas: 1, nombre: "Twin" },
      { numCamas: 1, nombre: "Sofá cama" },
    ],
    tamanyo: 75,
    servicios: ["Balcón", "Plancha", "AC", "TV", "Cafetera", "Nevera", "WiFi"],
    numPersonas: 4,
    precio: 250,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB007",
    nombre: "Bragi",
    categoria: "Premium",
    camas: [
      { numCamas: 1, nombre: "Double" },
      { numCamas: 1, nombre: "Twin" },
      { numCamas: 1, nombre: "Sofá cama" },
    ],
    tamanyo: 75,
    servicios: ["Balcón", "Plancha", "AC", "TV", "Cafetera", "Nevera", "WiFi"],
    numPersonas: 4,
    precio: 250,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB008",
    nombre: "Forseti",
    categoria: "Premium",
    camas: [
      { numCamas: 1, nombre: "Double" },
      { numCamas: 1, nombre: "Twin" },
      { numCamas: 1, nombre: "Sofá cama" },
    ],
    tamanyo: 75,
    servicios: ["Balcón", "Plancha", "AC", "TV", "Cafetera", "Nevera", "WiFi"],
    numPersonas: 4,
    precio: 250,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB009",
    nombre: "Vidar",
    categoria: "Premium",
    camas: [
      { numCamas: 1, nombre: "Double" },
      { numCamas: 1, nombre: "Twin" },
      { numCamas: 1, nombre: "Sofá cama" },
    ],
    tamanyo: 75,
    servicios: ["Balcón", "Plancha", "AC", "TV", "Cafetera", "Nevera", "WiFi"],
    numPersonas: 4,
    precio: 250,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB010",
    nombre: "Ullr",
    categoria: "Premium",
    camas: [
      { numCamas: 1, nombre: "Double" },
      { numCamas: 1, nombre: "Twin" },
      { numCamas: 1, nombre: "Sofá cama" },
    ],
    tamanyo: 75,
    servicios: ["Balcón", "Plancha", "AC", "TV", "Cafetera", "Nevera", "WiFi"],
    numPersonas: 4,
    precio: 250,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB011",
    nombre: "Sif",
    categoria: "Premium",
    camas: [
      { numCamas: 1, nombre: "Double" },
      { numCamas: 1, nombre: "Twin" },
      { numCamas: 1, nombre: "Sofá cama" },
    ],
    tamanyo: 75,
    servicios: ["Balcón", "Plancha", "AC", "TV", "Cafetera", "Nevera", "WiFi"],
    numPersonas: 4,
    precio: 250,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
      "https://i.ibb.co/Y4j3vtNL/premium-Room.png",
    ],
    habilitada: true,
  },

  {
    codigo: "HAB012",
    nombre: "Huginn",
    categoria: "Estándar Double",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB013",
    nombre: "Muninn",
    categoria: "Estándar Double",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB014",
    nombre: "Geri",
    categoria: "Estándar Double",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB015",
    nombre: "Rafn",
    categoria: "Estándar Double",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB016",
    nombre: "Valravn",
    categoria: "Estándar Double",
    camas: [{ numCamas: 1, nombre: "Double" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
      "https://i.ibb.co/pB1BV5gs/standard-Room.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB017",
    nombre: "Sköll",
    categoria: "Estándar Twin",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB018",
    nombre: "Dellingr",
    categoria: "Estándar Twin",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB019",
    nombre: "Svanr",
    categoria: "Estándar Twin",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB020",
    nombre: "Gjallar",
    categoria: "Estándar Twin",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
    ],
    habilitada: true,
  },
  {
    codigo: "HAB021",
    nombre: "Arvakr",
    categoria: "Estándar Twin",
    camas: [{ numCamas: 2, nombre: "Twin" }],
    tamanyo: 50,
    servicios: ["AC", "TV", "Cafetera", "Minibar", "WiFi"],
    numPersonas: 2,
    precio: 125,
    descripcion: "Lorem",
    imagenes: [
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
      "https://i.ibb.co/qYD28ySQ/standard-Room-twin.png",
    ],
    habilitada: true,
  },
]);
